INSERT INTO OWNER (ID,FIRST_NAME,LAST_NAME) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'John', 'Doe');
INSERT INTO OWNER (ID,FIRST_NAME,LAST_NAME) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Arturo', 'Marquez');
INSERT INTO OWNER (ID,FIRST_NAME,LAST_NAME) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Lance', 'Tyler');
INSERT INTO OWNER (ID,FIRST_NAME,LAST_NAME) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Andres', 'Marquez');

INSERT INTO PET (ID,NAME,BIRTH_DATE,OWNER_ID) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Bella', '2005-09-07', 1);
INSERT INTO PET (ID,NAME,BIRTH_DATE,OWNER_ID) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Kitty', '2008-08-06', 1);
INSERT INTO PET (ID,NAME,BIRTH_DATE,OWNER_ID) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Leo', '2001-04-17', 1);
INSERT INTO PET (ID,NAME,BIRTH_DATE,OWNER_ID) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Sam', '2009-03-07', 2);
INSERT INTO PET (ID,NAME,BIRTH_DATE,OWNER_ID) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Cleo', '2010-11-30', 2);
INSERT INTO PET (ID,NAME,BIRTH_DATE,OWNER_ID) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Cooper', '2010-01-20', 2);
INSERT INTO PET (ID,NAME,BIRTH_DATE,OWNER_ID) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Oreo', '2008-09-04', 3);
INSERT INTO PET (ID,NAME,BIRTH_DATE,OWNER_ID) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Murphy', '2008-09-04', 3);
INSERT INTO PET (ID,NAME,BIRTH_DATE,OWNER_ID) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Fiona', '2007-08-06', 3);
INSERT INTO PET (ID,NAME,BIRTH_DATE,OWNER_ID) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Romeo', '2009-02-24', 4);
INSERT INTO PET (ID,NAME,BIRTH_DATE,OWNER_ID) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Athena', '2000-03-09', 4);
INSERT INTO PET (ID,NAME,BIRTH_DATE,OWNER_ID) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Ruby', '2000-06-24', 4);
INSERT INTO PET (ID,NAME,BIRTH_DATE,OWNER_ID) VALUES (PETCLINIC_SEQUENCE.NEXTVAL, 'Theo', '2002-06-08', 4);